# Generated by Django 5.0.4 on 2024-05-06 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='is_deleted',
            new_name='is_active',
        ),
    ]
